apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl
  namespace: default 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubectl
  namespace: default 
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: default
      labels:
        app: kubectl
    spec:
      serviceAccount: kubectl
      containers:
      - image: sarathn2013/slack-hubot:latest 
        name: kubectl-slackbot
        env:
        - name: HUBOT_SLACK_TOKEN
          value: xoxb-218005899347-DlRwTJdKh2ICV37Uwcdzcz60
